name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into th Go module directory
      uses: actions/checkout@v2

    - name: Deps
      run: go get -v -t -d ./...

    - name: Vet
      run: go vet -v ./...

    - name: Unit
      run: go test -v -run Unit ./...
      
    - name: Integration
      run: go test -v -run Integration ./...